---
name: petclinic

releases:
- name: "pxc"
  version: "0.31.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/pxc-release?v=0.31.0"
  sha1: "d85b843d3e6e20711a6ca270eb62bad6a16bd22d"
- name: "bpm"
  version: "1.1.9"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.9"
  sha1: "dcf0582d838a73de29da273552ae79ac3098ee8b"
- name: spring-petclinic
  version: create
  url: file://.

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000

instance_groups:
- name: db
  instances: 1
  jobs:
  - name: pxc-mysql
    release: pxc
    properties:
      port: ((mysql-port))
      admin_password: ((mysql_admin_password))
      tls:
        galera: ((galera_server_certificate))
        server: ((mysql_server_certificate))
      seeded_databases:
        - name: &petclinic_db petclinic
          username: &petclinic_db_username petclinic
          password: ((petclinic_db_password))
    provides:
      mysql: {as: db_conn}
  vm_type: small
  stemcell: default
  networks: [{name: ((network))}]
  azs: [((db-az1))]
  persistent_disk: 10_240

- name: webapp
  instances: 1
  consumes:
    db: {from: db_conn}
  jobs:
  - name: spring-petclinic
    release: spring-petclinic
    properties:
      jre: 8
      port: ((spring-boot-port))
      db:
        name: *petclinic_db
        username: *petclinic_db_username
        password: ((petclinic_db_password))
  vm_type: small
  stemcell: default
  networks: [{name: ((network))}]
  azs: [((webapp-az1))]

variables:
- name: mysql_admin_password
  type: password
- name: pxc_galera_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_galera_ca
- name: pxc_server_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_server_ca
- name: galera_server_certificate
  type: certificate
  options:
    ca: pxc_galera_ca
    extended_key_usage: [ "server_auth", "client_auth" ]
    common_name: galera_server_certificate
- name: mysql_server_certificate
  type: certificate
  options:
    ca: pxc_server_ca
    common_name: mysql_server_certificate
- name: petclinic_db_password
  type: password
